"""A skeletal blackboard system.

The library supplies the board, the shared structure through which
independent agents contribute to one result, and the control component,
which determines which agents are notified of a change, whether a proposed
write is admitted, whether budgets hold, and when the run has finished. An
application creates a model by supplying its regions, agents, seed,
admission rule, termination predicate, and budgets. The public surface is
the set of names in ``__all__``; every other name is internal.
"""

from blackboard._board import (
    BlackboardError,
    Board,
    BoardChange,
    Conflict,
    Contribution,
    DuplicateRegionError,
    Level,
    RegionKindError,
    Register,
    RegisterState,
    UndeclaredRegionError,
    UnsetRegisterError,
    Written,
)
from blackboard._clock import Clock, ManualClock, ScheduledCall, SystemClock
from blackboard._control import (
    Aborted,
    Accept,
    Accepted,
    AdmissionRule,
    Agent,
    AuditEvent,
    BoardReader,
    BoardStore,
    BudgetExhausted,
    BudgetKind,
    BudgetReached,
    Complete,
    Control,
    DeadlineExtended,
    DuplicateAgentError,
    FinishedWithFailures,
    Notification,
    NotificationAcknowledged,
    NotificationDispatched,
    NotificationId,
    PresumedFailed,
    ProposedContribution,
    ProposedRegisterWrite,
    ProposedWrite,
    RegisterSeeded,
    Reject,
    Rejected,
    RejectionCause,
    RunBudgets,
    RunClosed,
    RunClosedError,
    RunOutcome,
    SeedError,
    TerminationDecision,
    TerminationPredicate,
    UnknownNotificationError,
    WakeCapReached,
    WriteAccepted,
    WriteRejected,
)
from blackboard._model import Model, create_model

__all__ = [
    "Aborted",
    "Accept",
    "Accepted",
    "AdmissionRule",
    "Agent",
    "AuditEvent",
    "BlackboardError",
    "Board",
    "BoardChange",
    "BoardReader",
    "BoardStore",
    "BudgetExhausted",
    "BudgetKind",
    "BudgetReached",
    "Clock",
    "Complete",
    "Conflict",
    "Contribution",
    "Control",
    "DeadlineExtended",
    "DuplicateAgentError",
    "DuplicateRegionError",
    "FinishedWithFailures",
    "Level",
    "ManualClock",
    "Model",
    "Notification",
    "NotificationAcknowledged",
    "NotificationDispatched",
    "NotificationId",
    "PresumedFailed",
    "ProposedContribution",
    "ProposedRegisterWrite",
    "ProposedWrite",
    "RegionKindError",
    "Register",
    "RegisterSeeded",
    "RegisterState",
    "Reject",
    "Rejected",
    "RejectionCause",
    "RunBudgets",
    "RunClosed",
    "RunClosedError",
    "RunOutcome",
    "ScheduledCall",
    "SeedError",
    "SystemClock",
    "TerminationDecision",
    "TerminationPredicate",
    "UndeclaredRegionError",
    "UnknownNotificationError",
    "UnsetRegisterError",
    "WakeCapReached",
    "WriteAccepted",
    "WriteRejected",
    "Written",
    "create_model",
]
